version: '2.3'

services:
  rest_go:
    container_name: rest_go
    image: abdil/go_rest:mac
    ports:
      - "8081:8081"

  # mysql:
  #   container_name: mysql-db1
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=kerjakansekarang
  #     - MYSQL_DATABASE=rest_golang
  #     - MYSQL_USER=user1
  #     - MYSQL_PASSWORD=user1
  #   ports: 
  #     - 3306:3306

  redis:
    container_name: redis-server1
    image: redis:latest
    ports:
      - 6379:6379